~VERSION INFORMATION 
VERS.                       3.0            :LAS - Fpwd las output with realtime data
WRAP.                        NO            :One line per step
DLM.                      COMMA            :Delimiting character
#
~Well Information Block 
#MNEM.UNIT            Data type            :Information
#______________________________________________________
STRT.ft                18279.94            :START INDEX
STOP.ft                18279.94            :STOP INDEX
STEP.                    0.0625            :STEP
NULL.                   -999.25            :NULL
COMP.            DUMMY COMP                      :Company Name
WELL.            DUMMY WELL                :Well Name
FLD.             DUMMY FIELD               :Field
CNTY.                                      :County or Rig
STAT.                 DUMMY STATE          :STATE
LOC.             DUMMY LOC                  :Location
API.                                       :Api number
LATI.            00° 00' 00.000" N         :Well Latitude
LONG.            00° 00' 00.000" W         :Longitude
GDAT.                       MSL            :Datum
DPRF.ft                18279.94            :Depth Reference
DATE.                 01-Jan-01            :Current Date
SRVC.              DUMMY CORP              :Service Company
EDF.ft                    81.99            :Elevation of Derrick Floor


~Parameter 
RUN.                          9            :Run {F}
TEST.                        16            :Test {F}
MD.FT                  18279.94            :Measured Depth {F}
TVD.FT                 16409.98            :Tvd of the test {F}
BHT.DEGF                    100            :Bottom Hole Temperature {F}
PROBE_TFO.DEG               330            :Probe Angle Offset {F}
BS.IN                       8.5            :Bit Size {F}
DFT_CATEGORY.               Oil            :Drilling Fluid Type {S}
DFT.              Synthetic Oil            :Drilling Fluid Oil Type {S}
RMS.OHMM                    500            :Resistivity of Mud Sample {F}
RMCS.OHMM                                  :Resistivity of Mud Cake Sample {F}
BSAL.PPM                      0            :Borehole Salinity {F}
BHK.%                         0            :Drilling Fluid Potassium Concentration {F}
DHGS.%                      9.4            :Drilling Fluid High Gravity Solids {F}
FPWD_OD.IN                 6.75            :FPWD Outside Diameter {F}
QUARTZGAUGE.               ACQG            :Primary Gauge Type {S}
STRAINGAUGE.              Paine            :Strain Gauge Type {S}



~Phase_A_Definition 
BAT_DEP_STATE.                             :Battery Condition with Depassivation {F}
AORIENT.deg                                :Phase A Probe Orientation {F}
ALONG_DL.                                  :Phase A Long Downlink feedback {F}
ASTATE.                                    :Phase A Tool State feedback {F}

~Phase_A_data | Phase_A_Definition 
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00
     0.00,   -48.00,   109.00,     2.00

~Phase_A_Parameter 
PHASE.    A     : Phase    {S}

~Phase_B_Definition 
BDIS.                                      :Phase B Discriminator Position {F}
BDIS_TIM.s                                 :Phase B Delta Pressure Time Stamp {F}
BP_DELTA.psi                               :Phase B Delta Pressure Measurement {F}
BT_DELTA.s                                 :Phase B Delta Pressure Time Stamp {F}

~Phase_B_data | Phase_B_Definition 
     5.00,     0.00,     3.74,     0.00
     5.00,     0.00,     3.74,     0.00
     5.00,     0.00,     3.74,     0.00
     6.00,     1.00,  9997.00,     1.00
     0.00,    29.00,  9983.74,    29.00
     5.00,    55.00,  9984.74,    55.00
     5.00,    63.00,  9983.74,    63.00
     5.00,    71.00, 10028.74,    71.00
     5.00,    80.00, 10025.74,    80.00
     5.00,    94.00, 10016.74,    94.00
     6.00,    95.00,  9992.00,    95.00
     5.00,   109.00,  9103.74,   109.00
     5.00,   118.00,  8701.74,   118.00
     5.00,   132.00,  8703.74,   132.00
     5.00,   139.00,  8703.74,   139.00
     1.00,   123.00,  8701.74,   123.00
     5.00,   156.00,  8703.74,   156.00
     6.00,   157.00,  9993.00,   157.00
     5.00,   178.00,  8703.74,   178.00
     5.00,   186.00,  8703.74,   186.00
     5.00,   195.00,  8703.74,   195.00
     5.00,   210.00,  8703.74,   210.00
     5.00,   217.00,  8703.74,   217.00
     5.00,   225.00,  8703.74,   225.00
     6.00,   226.00,  9986.00,   226.00
     5.00,   248.00,  8701.74,   248.00
     2.00,   244.00,  8703.74,   244.00
     5.00,   263.00,  8701.74,   263.00
     5.00,   271.00,  8703.74,   271.00
     5.00,   285.00,  8703.74,   285.00
     5.00,   292.00,  8703.74,   292.00
     6.00,   293.00,  9988.00,   293.00
     5.00,   310.00,  8704.74,   310.00
     5.00,   324.00,  8704.74,   324.00
     5.00,   331.00,  8703.74,   331.00
     5.00,   339.00,  8703.74,   339.00
     5.00,   348.00,  8703.74,   348.00
     5.00,   362.00,  8703.74,   362.00
     6.00,   363.00,  9991.00,   363.00
     3.00,   263.00,  8701.74,   263.00
     5.00,   386.00,  8703.74,   386.00
     5.00,   400.00,  8704.74,   400.00
     5.00,   408.00,  9337.74,   408.00
     4.00,   406.00,  8703.74,   406.00
     5.00,   425.00, 10024.74,   425.00
     6.00,   426.00,  9987.00,   426.00
     5.00,   446.00,  9988.74,   446.00

~Phase_B_Parameter 
PHASE.    B     : Phase    {S}
BP_HY_B4.psi          9983.74:  Phase B Hydrostatic Pressure before test {F}
BT_HY_B4.s            29.00:  Phase B Hydrostatic Pressure before test Time Stamp {F}
BP_IV_DR.psi          8701.74:  Phase B Investigation Drawdown Pressure {F}
BT_IV_DR.s           123.00:  Phase B Investigation Drawdown Pressure Time Stamp {F}
BP_IV_BU.psi          8703.74:  Phase B Investigation Buildup Pressure {F}
BT_IV_BU.s           244.00:  Phase B Investigation Buildup Pressure Time Stamp {F}
BP_FN_DR.psi          8701.74:  Phase B Final Drawdown Pressure {F}
BT_FN_DR.s           263.00:  Phase B Final Drawdown Pressure Time Stamp {F}
BP_FN_BU.psi          8703.74:  Phase B Final Buildup Pressure {F}
BT_FN_BU.s           406.00:  Phase B Final Buildup Pressure Time Stamp {F}
BP_CORR.psi             3.74:  Phase B Hydraulic Head Correction {F}
B_STATE.          -999.25:  Phase B State Machine Description {F}
B_RETRACT.          -999.25:  Phase B Deployed/Retract Status {F}

~Phase_C_Parameter 
PHASE.    C     : Phase    {S}
TIME.HH.MM.SS         19:09:15:  Test time {S}
DATE.DATE        29-Feb-20:  Test date {S}
DEPTH.ft         18279.94: Depth Index {F}
TVD.ft         16409.98:  True Vertical Depth {F}
STATUS1.        Retracted:  Status Flag One {F}
STATUS1T.s           538.78:  Status Flag One Time Stamp {F}
CP_FN_BU.psi          8704.24:  Phase C Final Buildup Pressure {F}
Q_60S.psi/min             0.01:  Quality 60s slope {F}
Q_TEST.           116.00:  Quality of Test indicator {F}
Q_PRSVAR.psi             0.29:  Quality Pressure Variance {F}
BAT_DEP_STATE.             0.00:  Battery Condition with Depassivation {F}
STATUS2.        Retracted:  Status Flag Two {F}
STATUS2T.s           564.17:  Status Flag Two Time Stamp {F}
CP_IV_BU.psi          8704.24:  Phase C Investigation Buildup Pressure {F}
CP_HY_B4.psi          9985.24:  Phase C Hydrostatic Pressure before Test {F}
CP_FN_DR.psi          8703.24:  Phase C Final Drawdown Pressure {F}
CP_IV_DR.psi          8703.24:  Phase C Investigation Drawdown Pressure {F}
STATUS3.        Retracted:  Status Flag Three {F}
STATUS3T.s           579.53:  Status Flag Three Time Stamp {F}
CT_IV_BU.s           243.00:  Phase C Investigation Buildup Pressure Time Stamp {F}
CT_FN_DR.s           263.00:  Phase C Final Drawdown Pressure Time Stamp {F}
CT_FN_BU.s           405.00:  Phase C Final Buildup Pressure Time Stamp {F}
CT_IV_DR.s           123.60:  Phase C Investigation Drawdown Pressure Time Stamp {F}
CT_EXPON.             3.94:  Phase C Time Exponent for Deltas {F}
STATUS4.        Retracted:  Status Flag Four {F}
STATUS4T.s           600.34:  Status Flag Four Time Stamp {F}
CP_DELTA1.psi          8706.24:  Phase C Delta Pressure First Position {F}
CP_DELTA2.psi          8705.24:  Phase C Delta Pressure Second Position {F}
CP_DELTA3.psi          8704.24:  Phase C Delta Pressure Third Position {F}
CP_DELTA4.psi          8705.24:  Phase C Delta Pressure Fourth Position {F}
CP_DELTA5.psi          8704.24:  Phase C Delta Pressure Fifth Position {F}
CT_DELTA1.s           263.50:  Phase C Delta Pressure Time Stamp First Position {F}
CT_DELTA2.s           264.97:  Phase C Delta Pressure Time Stamp Second Position {F}
CT_DELTA3.s           270.76:  Phase C Delta Pressure Time Stamp Third Position {F}
CT_DELTA4.s           293.58:  Phase C Delta Pressure Time Stamp Fourth Position {F}
CT_DELTA5.s           383.49:  Phase C Delta Pressure Time Stamp Fifth Position {F}
C_MOB_FN.mD/cP           560.76:  Phase C Final Mobility {F}
PRETEST.             9.00:  PreTest Code {F}
STATUS5.        Retracted:  Status Flag Five {F}
STATUS5T.s           617.10:  Status Flag Five Time Stamp {F}
FP_EQMW.g/cm3             1.22:  Formation Pressure Equivalent Mud Weight {F}
AORIENT.deg           -48.00:  Phase A Probe Orientation {F}
